In [2]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

## Q1

Yes, there is a difference in the data types of list_ and array_list.


list_ is a Python list.
array_list is a NumPy array created using the np.array function, which converts the elements of the Python list to a NumPy array.

In [3]:
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))

Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>


## Q2

In [4]:
print("Data types of elements in list_:")
for element in list_:
    print(f"{element}: {type(element)}")

Data types of elements in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>


In [5]:
print("\nData types of elements in array_list:")
for element in array_list:
    print(f"{element}: {type(element)}")


Data types of elements in array_list:
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


## Q3

In [7]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("\nData types of elements in array_list:")
for element in array_list:
    print(f"{element}: {type(element)}")


Data types of elements in array_list:
1: <class 'numpy.int64'>
2: <class 'numpy.int64'>
3: <class 'numpy.int64'>
4: <class 'numpy.int64'>
5: <class 'numpy.int64'>


## Q4

In [8]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


## Q5

In [9]:
zero_matrix = np.zeros((3, 3))
print("3x3 Matrix of Zeros:")
print(zero_matrix)

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6

In [10]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
